name: CI/CD
on:
  push:
    branches:
      - main
    paths:
      - "src/**"
      - "next.config.js"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: npm install
      - name: Build
        run: npm run build
      - name: Deploy to Xserver
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.XSERVER_HOST }}
          username: ${{ secrets.XSERVER_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "out/*"
          target: "/home/daiki9548/d-note.org/public_html"
      - name: Deploy with rsync
        run: rsync -auzrv -e "ssh -i key -o UserKnownHostsFile=/dev/null -StrictHostKeyChecking=no -p 10022" --delete ./out/* ${{ secrets.XSERVER_USERNAME }}@${{ secrets.XSERVER_HOST }}:/home/daiki9548/d-note.org/public_html --exclude .htaccess
